# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BranchAWS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BranchAWS
   pod 'AWSAPIGateway', '~> 2.6.29'
   pod 'react-native-branch', :path => '../node_modules/react-native-branch'
   pod 'Branch-SDK', path: '../node_modules/react-native-branch/ios'

end
